import type { Metadata } from "next";
import { Geist, Geist_Mono, Cormorant_Garamond, Montserrat, Roboto } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({ 
  subsets: ['latin'],
  variable: '--font-serif',
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-sans',
  weight: ['300', '400', '500'],
});

const roboto = Roboto({
  weight: ['300', '400', '500', '700'], // Escolha os pesos que vai usar
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto', // Definimos uma variável CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt" className={`${cormorant.variable} ${roboto.variable}`}>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
